api_platform:
    title: Worktide API
    description: Worktide — Project/Task/Time/CRM-Management API
    version: 0.1.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        pagination_items_per_page: 30
        pagination_client_items_per_page: true
        pagination_maximum_items_per_page: 200
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
        html: ['text/html']
    docs_formats:
        jsonld: ['application/ld+json']
        jsonopenapi: ['application/vnd.openapi+json']
        html: ['text/html']
