<?php

declare(strict_types=1);

namespace App\Entity;

use ApiPlatform\Doctrine\Orm\Filter\SearchFilter;
use ApiPlatform\Metadata\ApiFilter;
use ApiPlatform\Metadata\ApiResource;
use ApiPlatform\Metadata\Delete;
use ApiPlatform\Metadata\Get;
use ApiPlatform\Metadata\GetCollection;
use ApiPlatform\Metadata\Patch;
use App\Entity\Enum\ConflictPolicy;
use App\Entity\Enum\SyncMode;
use App\Entity\Trait\AuditableTrait;
use App\Entity\Trait\EntityIdTrait;
use App\Entity\Trait\TimestampableTrait;
use App\Entity\Trait\VersionedTrait;
use App\Entity\Trait\WorkspaceScopedTrait;
use App\Repository\EntitySyncRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Uid\Uuid;

/**
 * One mapping row between a Worktide entity and its mirror in an
 * external system. Replaces and generalises the per-entity
 * {@see Trait\ExternalReferenceTrait} for cases that need:
 *
 *   - M:N. A single Worktide Task can be mirrored in Jira AND
 *     Redmine AND a CalDAV calendar simultaneously — three
 *     EntitySync rows, one per channel.
 *   - Bidirectional sync state. The trait only carried a flat ID;
 *     this entity carries `externalUpdatedAt` + `ourVersion` + `etag`
 *     so adapters can detect dual-changes and apply
 *     {@see ConflictPolicy}.
 *   - Pause without un-mapping. `syncMode = Disabled` keeps the
 *     mapping intact while halting reads/writes — useful during
 *     debugging or partial migrations.
 *
 * The (entityType, entityId) pair carries the **identity** of the
 * Worktide-side record; entityType is a free-form string slug
 * (`task`, `project`, `customer`, `time_entry`, `calendar_event`)
 * so we don't have to invent a discriminator hierarchy for every
 * future entity that becomes syncable.
 *
 * UNIQUE(channel, externalId) makes a single external record map
 * to at most one local entity per channel; the inverse is allowed
 * (one local entity in N channels), which is exactly the M:N we
 * want.
 */
#[ORM\Entity(repositoryClass: EntitySyncRepository::class)]
#[ORM\Table(name: 'entity_syncs')]
#[ORM\UniqueConstraint(name: 'entity_sync_channel_external_unique', columns: ['channel_id', 'external_id'])]
#[ORM\Index(name: 'entity_sync_workspace_idx', columns: ['workspace_id'])]
#[ORM\Index(name: 'entity_sync_entity_idx', columns: ['entity_type', 'entity_id'])]
#[ORM\Index(name: 'entity_sync_channel_idx', columns: ['channel_id'])]
#[ORM\HasLifecycleCallbacks]
#[ApiResource(
    shortName: 'EntitySync',
    operations: [
        new GetCollection(),
        new Get(),
        new Patch(),
        new Delete(),
    ],
    mercure: true,
)]
#[ApiFilter(SearchFilter::class, properties: [
    'workspace' => 'exact',
    'channel' => 'exact',
    'entityType' => 'exact',
    'entityId' => 'exact',
    'externalId' => 'exact',
    'syncMode' => 'exact',
])]
class EntitySync
{
    use EntityIdTrait;
    use TimestampableTrait;
    use WorkspaceScopedTrait;
    use VersionedTrait;
    use AuditableTrait;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false, onDelete: 'CASCADE')]
    private Channel $channel;

    /**
     * Worktide-side entity type slug — `task`, `comment`,
     * `time_entry`, `calendar_event`, … Free-form so new
     * syncable entities don't need an enum migration. The
     * adapter knows what it can sync; the resolver maps the slug
     * back to the Doctrine class.
     */
    #[ORM\Column(length: 40)]
    private string $entityType;

    /**
     * UUID of the Worktide-side entity. Foreign-key constraint
     * cannot be expressed at the DB level because entityType is
     * polymorphic — referential integrity is enforced by the
     * adapter that creates/deletes mappings.
     */
    #[ORM\Column(type: 'uuid')]
    private Uuid $entityId;

    /**
     * Identifier on the external side — Jira issue key
     * (`PROJ-123`), Redmine issue id (`4567`), Google Calendar
     * event id (long opaque string), etc.
     */
    #[ORM\Column(length: 200)]
    private string $externalId;

    /**
     * URL the user can click to open the record on the external
     * system. Generated by the adapter at sync time so the SPA
     * can render "Open in Jira" without re-deriving the URL
     * shape from the channel config.
     */
    #[ORM\Column(length: 500, nullable: true)]
    private ?string $externalUrl = null;

    /**
     * `updated_at` value reported by the external system at the
     * last sync. Lets the adapter detect "did the external change
     * since we last saw it?" without re-pulling the full payload.
     */
    #[ORM\Column(type: 'datetime_immutable', nullable: true)]
    private ?\DateTimeImmutable $externalUpdatedAt = null;

    /**
     * Snapshot of the Worktide-side `version` field at the last
     * sync. Combined with `externalUpdatedAt` this is the basis
     * for the conflict-detection in {@see ConflictPolicy}.
     */
    #[ORM\Column(type: 'integer', nullable: true)]
    private ?int $ourLastSyncedVersion = null;

    /**
     * ETag or hash returned by the external system — useful for
     * If-None-Match conditional pulls (Jira, Microsoft Graph) so
     * we don't refetch unchanged records.
     */
    #[ORM\Column(length: 100, nullable: true)]
    private ?string $etag = null;

    #[ORM\Column(length: 16, enumType: SyncMode::class, options: ['default' => 'bidirectional'])]
    private SyncMode $syncMode = SyncMode::Bidirectional;

    #[ORM\Column(length: 24, enumType: ConflictPolicy::class, options: ['default' => 'manual'])]
    private ConflictPolicy $conflictPolicy = ConflictPolicy::Manual;

    #[ORM\Column(type: 'datetime_immutable', nullable: true)]
    private ?\DateTimeImmutable $lastSyncedAt = null;

    #[ORM\Column(type: 'datetime_immutable', nullable: true)]
    private ?\DateTimeImmutable $lastReconciledAt = null;

    #[ORM\Column(type: 'text', nullable: true)]
    private ?string $lastSyncError = null;

    /**
     * Adapter-specific blob. Holds field-mapping cache, vendor-
     * specific IDs that aren't the main externalId (Jira renderer
     * variants, Redmine project_id, etc.). Treat as opaque from
     * the application layer.
     *
     * @var array<string, mixed>
     */
    #[ORM\Column(type: 'json')]
    private array $sourceMetadata = [];

    public function getChannel(): Channel { return $this->channel; }
    public function setChannel(Channel $c): self { $this->channel = $c; return $this; }

    public function getEntityType(): string { return $this->entityType; }
    public function setEntityType(string $t): self { $this->entityType = $t; return $this; }

    public function getEntityId(): Uuid { return $this->entityId; }
    public function setEntityId(Uuid $id): self { $this->entityId = $id; return $this; }

    public function getExternalId(): string { return $this->externalId; }
    public function setExternalId(string $id): self { $this->externalId = $id; return $this; }

    public function getExternalUrl(): ?string { return $this->externalUrl; }
    public function setExternalUrl(?string $u): self { $this->externalUrl = $u; return $this; }

    public function getExternalUpdatedAt(): ?\DateTimeImmutable { return $this->externalUpdatedAt; }
    public function setExternalUpdatedAt(?\DateTimeImmutable $t): self { $this->externalUpdatedAt = $t; return $this; }

    public function getOurLastSyncedVersion(): ?int { return $this->ourLastSyncedVersion; }
    public function setOurLastSyncedVersion(?int $v): self { $this->ourLastSyncedVersion = $v; return $this; }

    public function getEtag(): ?string { return $this->etag; }
    public function setEtag(?string $e): self { $this->etag = $e; return $this; }

    public function getSyncMode(): SyncMode { return $this->syncMode; }
    public function setSyncMode(SyncMode $m): self { $this->syncMode = $m; return $this; }

    public function getConflictPolicy(): ConflictPolicy { return $this->conflictPolicy; }
    public function setConflictPolicy(ConflictPolicy $p): self { $this->conflictPolicy = $p; return $this; }

    public function getLastSyncedAt(): ?\DateTimeImmutable { return $this->lastSyncedAt; }
    public function setLastSyncedAt(?\DateTimeImmutable $t): self { $this->lastSyncedAt = $t; return $this; }

    public function getLastReconciledAt(): ?\DateTimeImmutable { return $this->lastReconciledAt; }
    public function setLastReconciledAt(?\DateTimeImmutable $t): self { $this->lastReconciledAt = $t; return $this; }

    public function getLastSyncError(): ?string { return $this->lastSyncError; }
    public function setLastSyncError(?string $e): self { $this->lastSyncError = $e; return $this; }

    /** @return array<string, mixed> */
    public function getSourceMetadata(): array { return $this->sourceMetadata; }
    /** @param array<string, mixed> $m */
    public function setSourceMetadata(array $m): self { $this->sourceMetadata = $m; return $this; }
}
